export enum RolEnum {
    ROLE_DOCENTE = 'ROLE_DOCENTE',
  ROLE_AUTORIDAD = 'ROLE_AUTORIDAD',
  ROLE_PADRE = 'ROLE_PADRE',
  ROLE_PERSONAL = 'ROLE_PERSONAL',
  ROLE_ESTUDIANTE = 'ROLE_ESTUDIANTE',
  ROLE_NO_REGISTRADO = 'ROLE_NO_REGISTRADO',
}
